name: Build Docker Image for MS1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show directory structure for debugging
        run: |
          echo "PWD = $(pwd)"
          ls -R

      - name: Configure AWS credentials (from GitHub Secrets)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (MS1)
        run: |
          cd microservice-1
          docker build -t ms1:latest .
