name: Build Docker Image for MS1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (MS1)
        run: |
          docker build \
            -t my-microservice:latest \
            -f microserives-k8s/microservice-1/Dockerfile \
            microserives-k8s/microservice-1
